server.port=8012
spring.application.name=farmasync-gateway

# Configuración de rutas SIN StripPrefix
spring.cloud.gateway.routes[0].id=usuarios-service
spring.cloud.gateway.routes[0].uri=http://localhost:8013
spring.cloud.gateway.routes[0].predicates[0]=Path=/farmasync/usuarios/**

spring.cloud.gateway.routes[1].id=pedidos-service
spring.cloud.gateway.routes[1].uri=http://localhost:8014
spring.cloud.gateway.routes[1].predicates[0]=Path=/farmasync/pedidos/**

spring.cloud.gateway.routes[2].id=ventas-service
spring.cloud.gateway.routes[2].uri=http://localhost:8015
spring.cloud.gateway.routes[2].predicates[0]=Path=/farmasync/ventas/**

spring.cloud.gateway.routes[3].id=inventario-service
spring.cloud.gateway.routes[3].uri=http://localhost:8016
spring.cloud.gateway.routes[3].predicates[0]=Path=/farmasync/inventario/**

# Actuator configuration
management.endpoints.web.exposure.include=health,gateway,info,metrics
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG

# SpringDoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html